### ISSUE TITLE
Support query strings in import urls.

### ISSUE THREAD

**Issue by NathanSMB** [justjavac/typescript-deno-plugin#13]
**Is your feature request related to a problem? Please describe.**

Currently you can not use query strings with import urls. Instead I get the error, "Cannot find module".

**Describe the solution you'd like**

For the purpose of this extension I believe it would be best to just return the expected module name without the query string when calling stripExtNameDotTs().

**Additional context**

I toyed around with this and came up with a fix in my own branch.

https://github.com/NathanSMB/typescript-deno-plugin/tree/feature/support-query-in-url

If this seems like an adequate fix to you I would be happy to create a pull request.

**Comment by justjavac** [comment]
THX
