### ISSUE TITLE
Top Level Await

### ISSUE THREAD

**Issue by brandonkal** [justjavac/typescript-deno-plugin#19]
**Describe the bug**

With VSCode Typescript 3.7.3 and Deno Typescript Complains.
https://github.com/microsoft/TypeScript/pull/35813

**To Reproduce**

Create a `tla.ts` file in an empty directory. VSCode complains
```
await Deno.chmod('path', 0o666)
```

**Expected behavior**

TLA is allowed as Deno allows it.

**Screenshots**

### Versions

latest extension
Typescript 3.7.3
Deno 0.28.1

**Comment by KyleJune** [comment]
Top level await will be supported when VS Code updates to using TypeScript 3.8+. I found you submitted another issue on the vscode-deno repository and that was the answer from there. Linking it below for anyone else that might come across this looking for an answer.

https://github.com/justjavac/vscode-deno/issues/63#issuecomment-575366756
