### ISSUE TITLE
Function 'convertRemoteToLocalCache'  hasn't take 'mod.ts.headers.json' into account

### ISSUE THREAD

**Issue by briefguo** [justjavac/typescript-deno-plugin#2]
**Describe the bug**

Function 'convertRemoteToLocalCache'  hasn't take 'mod.ts.headers.json' into account

**To Reproduce**

100%

**Expected behavior**

Intellisense works well as module 'http'

**Screenshots**

![image](https://user-images.githubusercontent.com/9976575/56075054-c29a4300-5dee-11e9-9624-13323d5b0918.png)
![image](https://user-images.githubusercontent.com/9976575/56075107-c8445880-5def-11e9-8672-cd99b45f1483.png)
![image](https://user-images.githubusercontent.com/9976575/56075198-3fc6b780-5df1-11e9-828c-08046289a601.png)
![image](https://user-images.githubusercontent.com/9976575/56075202-51a85a80-5df1-11e9-8611-080b12401069.png)
![image](https://user-images.githubusercontent.com/9976575/56075224-a3e97b80-5df1-11e9-98be-64383c8dec35.png)

### Versions

```
deno: 0.3.7
v8: 7.4.238
typescript: 3.4.1
```
**Additional context**

none

**Comment by justjavac** [comment]
work in progress

**Comment by bios21** [comment]
Also has the issue, I've made a proposal with this PR #3
