### ISSUE TITLE
JetBrains IDEs Installation

### ISSUE THREAD

**Issue by xmclark** [justjavac/typescript-deno-plugin#25]
# Problem

The README does not contain install instructions for JetBrains IDEs.

# Solution

Add install instructions for JetBrains IDEs to the README.

# Additional Context

While trying out [Deno](https://deno.land), I noticed that my preferred IDE did not have language support by default. I found this plugin and saw support for VSCode but no instructions for WebStorm. 

I found you can configure WebStorm to use the use the local workspace installation for the language service. This solution should work for any JetBrains IDEs configured with the TypeScript plugin.

**Comment by xmclark** [comment]
I have a draft PR ready with the installation instructions.

**Comment by justjavac** [comment]
thx

**Comment by Himself65** [comment]
@xmclark any instructions now? I'm trying to use `Deno` on Webstrom

**Comment by alfredosalzillo** [comment]
I have followed the instruction on the #26 but don't work for me, with webstorm 2019.3.3 on ubuntu.
