### ISSUE TITLE
How to use with VS Code's version of TypeScript?

### ISSUE THREAD

**Issue by jsejcksn** [justjavac/typescript-deno-plugin#36]
I don't want to use the VS Code extension at this time, but I am using VS Code's version of TypeScript, not a workspace version of TypeScript.

How can I configure and use this plugin in this case?

**Comment by justjavac** [comment]
Sorry, there is not a way to use VS Code's version of TypeScript with this plugin.

**Comment by jsejcksn** [comment]
@justjavac Why not? It's reading the same `tsconfig.json` file.

**Comment by justjavac** [comment]
https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#testing-locally

> **Note**: If you're using Visual Studio Code, you'll have to use the first approach above, with a path to the module, or run the "TypeScript: Select TypeScript Version" command and choose "Use Workspace Version", or click the version number between "TypeScript" and 😃 in the lower-right corner. Otherwise, VS Code will not be able to find your plugin.

there is a way, setting  VS Code's typescript:

```json
{
  "typescript.tsserver.pluginPaths": []
}
```
