### ISSUE TITLE
enable VS Code extensions，other project will show ts error

### ISSUE THREAD

**Issue by snowtreetree** [justjavac/typescript-deno-plugin#41]
**Describe the bug**

When I enable VS Code extensions，my project not base deno , will show ts error

**To Reproduce**
![image](https://user-images.githubusercontent.com/30932683/82200595-c83b5400-9931-11ea-9ba9-133465f99ab4.png)

**Expected behavior**

I do not know if some options I need to config

**Screenshots**

👆

### Versions

deno: 1.0.0
vscode: 1.45.1
typescript-deno-plugin: 1.28.0

**Additional context**

**Comment by justjavac** [comment]
https://github.com/denoland/vscode_deno/issues/39#issuecomment-629892685
