### ISSUE TITLE
I cannot find the Deno plugin in the workspace settings

### ISSUE THREAD

**Issue by jerry4718** [justjavac/typescript-deno-plugin#64]
I want to set an independent enable/disable for each src in the workspace, but I cannot find the Deno plugin in the workspace settings

**Comment by justjavac** [comment]
please install https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno

**Comment by jerry4718** [comment]
Not so, I can use the Deno plugin in the project, but after I add my front-end project using "Add Folder to Workspace", I don't know how to block the Deno plugin for the front-end project, I set it like this

```json
{
	"folders": [
		{
			"path": "src",
			"settings": {
				"deno.enable": false
			}
		},
		{
			"path": "server-deno",
			"settings": {
				"deno.enable": true
			}
		},
		{
			"path": "kits",
			"settings": {
				"deno.enable": false
			}
		}
	]
}
```

**Comment by justjavac** [comment]
Maybe in the future we will consider adding support for multiple workspaces

**Comment by jerry4718** [comment]
It's awkward, I should have called it "multiple workspaces" to be more clear, but still thank you for your understanding, and I'm sorry I submitted the issue using Google Translate

**Comment by justjavac** [comment]
@jerry4718 let's talk on wechat, my id: justjavac
